server:
  port: ${SERVER_PORT:8666}

spring:
  datasource:
    hikari:
      jdbc-url: ${JDBC_URL:jdbc:h2:file:~/db/h2/balance}
      username: ${JDBC_USERNAME:sa}
      password: ${JDBC_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: qed-bank-balance
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
